# Generated by Django 5.2.5 on 2025-08-11 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_instructor_course_lesson_choice_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='instractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.instructor'),
        ),
    ]
