# Generated by Django 5.2.5 on 2025-08-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_instractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='instractor',
            new_name='instructor',
        ),
    ]
