# Generated by Django 5.2.5 on 2025-08-13 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_instractor_lesson_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student',
        ),
    ]
