# Generated by Django 5.2.5 on 2025-08-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_enrollment_options_course_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(),
        ),
    ]
