# Generated by Django 5.2.5 on 2025-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Guest', 'Guest'), ('student', 'student'), ('instructor', 'instructor'), ('admin', 'admin')], default='Guest', max_length=10),
        ),
    ]
