# Generated by Django 5.2.5 on 2025-08-18 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
        ('accounts', '0002_customuser_otp_customuser_otp_expiry_and_more'),
    ]

    operations = [
    ]
