# Generated by Django 5.2.5 on 2025-08-20 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordresetcode_code'),
        ('accounts', '0004_customuser_is_verified'),
    ]

    operations = [
    ]
